openapi: 3.0.1
info:
  title: Swagger API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000/api'
paths:
  /some:
    get:
      tags:
        - Some
      summary: Get all data
      operationId: getAllData
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
               type: array
               items:
                 $ref: '#/components/schemas/Some'

components:
  schemas:
    Some:
      type: object
      properties:
        title:
          type: string
      xml:
        name: Some
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    ApiResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        data:
          type: object
